export enum ROUTES {
  landing = "/",
  roleLogin = "/login",
  firstAdminSetup = "/first-admin-setup",
  customerLogin = "/customer-login",
  register = "/register",
  adminDashboard = "/admin/dashboard",
  adminUsers = "/admin/users",
  adminCreateAdmin = "/admin/admins/new",
  adminHairstyles = "/admin/hairstyles",
  adminReports = "/admin/reports",
  adminSettings = "/admin/settings",
  createAdminHelp = "/create-admin",
  customerDashboard = "/customer/dashboard",
  customerAnalyze = "/customer/analyze",
  customerHistory = "/customer/history",
  customerFavorites = "/customer/favorites",
  customerProfile = "/customer/profile",
}
